version: 0.0
os: linux
files:
   - source: /
     destination: /elb/www/gogrillion.com/
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
#hooks:
#   BeforeInstall:
#    - location: scripts/installapache.sh
#      runas: root
#    - location: scripts/startapache.sh
#      runas: root
#   AfterInstall:
#    - location: scripts/restartapache.sh
#      runas: root